import { BaseSection } from '../../sections/BaseSection';
import { BaseCollectionSectionObservable } from './BaseCollectionSectionObservable';
import { ObservableArray } from 'tns-core-modules/data/observable-array';
import { FilterActionResult } from '../../controls/IFilterable';
import { ExecuteSource } from '../../common/ExecuteSource';
import { ODataAction } from '../../actions/ODataAction';
export declare abstract class BaseTableSectionObservable extends BaseCollectionSectionObservable {
    private _data;
    private _dataLoader;
    private _dataReadPageSize;
    private _isDataFromITargetServiceSpecifier;
    private _searchKeys;
    private _usesExtensions;
    private _extensionRatio;
    private _extensionMaxWidth;
    private _extensionHeight;
    private _isAFullPageList;
    private _highlightSelectedItem;
    private _isWithinFlexibleColumnLeadingPage;
    private _isFlexibleColumnLeadingPageActive;
    private _selectionModeKey;
    private _longPressToEnableKey;
    private _exitOnLastDeselectKey;
    private _dataPagingObject;
    protected _dataPaging: string;
    private _bindingContext;
    private _searchString;
    private _currentFilter;
    private _currentOrderBy;
    private _originalOrderBy;
    private _boundItems;
    private _originalService;
    private _selectedItem;
    private _pendingRedraw;
    private _loadMoreItemsFlag;
    private _readLinks;
    private _insertDeleteFlag;
    private _selectedItems;
    private _selectedRows;
    private _selectionMode;
    private _changedItem;
    readonly searchString: string;
    constructor(section: BaseSection);
    bind(): Promise<any>;
    readonly binding: any;
    bindInitialItems(): Promise<any>;
    getOrderBy(): string;
    filterUpdated(filterQuery: FilterActionResult): Promise<any>;
    getItem(index: number): any;
    getBoundData(row: number): any;
    isDataBounded(row: number): boolean;
    readonly selectedItem: any;
    loadMoreItems(): Promise<any>;
    onDataChanged(action: ODataAction, result: any): Promise<any>;
    redraw(): Promise<any>;
    resetDataChangedFlag(): void;
    onPress(row: any, action: string): Promise<any>;
    onSwipe(row: any): Promise<any>;
    getLeftKey(row: any): string[];
    getRightKey(row: any): string[];
    searchUpdated(searchText: string): Promise<any>;
    protected abstract _bindRowProperties(row: number, bindingObject: any, definition: any): Promise<any>;
    protected abstract _definitionUsesStaticCells(): boolean;
    protected abstract _getRowOnPressAction(row: number, action: string, source: ExecuteSource): string;
    protected abstract _getSearchKeys(): string[];
    protected _createStaticCellsData(): Promise<ObservableArray<any>>;
    protected isSectionEmpty(): boolean;
    protected _definitionForRow(row: number): any;
    protected _bindValues(bindingObject: any, definition: any): Promise<any>;
    protected _resolveData(definition: any): Promise<ObservableArray<any>>;
    protected _performRedraw(): Promise<any>;
    private _getVisibleSectionCount;
    private _getSectionIndex;
    private _onPressFunc;
    protected _onSwipeFunc(row: any): Promise<any>;
    protected _getOnSwipeAction(row: number, key: string): string;
    protected _getLeftKey(row: any): string[];
    protected _getRightKey(row: any): string[];
    protected onSelectionChanged(param: any): Promise<any>;
    protected setSelectionMode(mode: any): void;
    protected onSelectionModeChanged(param: any): Promise<any>;
    protected updateSectionSelectedRows(params: any): void;
    protected updateSelectedItems(): void;
    private _removeCheckedProperty;
    protected getSelectionMode(): any;
    protected getSelectionChangedItem(): any;
    protected getSelectedItems(): any;
    private _bindAdditionalCell;
    private _bindRow;
    private readonly _filtering;
    private readonly _retrieveSearchKeys;
    private _isFullPageList;
    private _isItemBound;
    private _resetData;
    private readonly originalService;
    private readonly _searching;
    private _setMaxItems;
    private _newServiceWithSearchAndFilterQueryOptions;
    private readonly _sorting;
    private _sorterMethod;
    private _getRowIndexByReadLink;
    private _removeOptionsFromQuery;
    private _redrawRows;
}
