export declare class ODataServiceUtils {
    private static propertyName;
    static getServiceName(serviceUrl: string): string;
    static hasPathSuffix(serviceUrl: string): Boolean;
    static convert(name: string, value: any, type: number): any;
    static base64StringToBinary(value: string): any;
    private static DATE_TIME_REGEX;
    private static UTC_DATE_TIME_REGEX;
    private static UTC_DATE_TIME_FULL_REGEX;
    private static DATE_REGEX;
    private static TIME_REGEX;
    private static TIME_FULL_REGEX;
    private static timeZoneAbbreviationForString;
    private static isNumericTypeWithEmptyValue;
    private static convertString;
    private static convertInteger;
    private static convertByte;
    private static convertBool;
    private static convertChar;
    private static convertDecimal;
    private static convertDouble;
    private static convertFloat;
    private static convertInt;
    private static convertShort;
    private static convertLong;
    private static convertUnsignedByte;
    private static convertLocalDateTime;
    private static convertGlobalDateTime;
    private static convertLocalDate;
    private static convertLocalTime;
    private static convertGUID;
    private static convertDayTimeDuration;
    private static globalDateTimeFrom;
    private static localDateTimeFrom;
    private static localDateFrom;
    private static localTimeFrom;
    private static utcDateTimeFromString;
    private static utcDateFromString;
    private static utcTimeFromString;
}
