import { BaseJSONDefinition } from '../BaseJSONDefinition';
export declare class BaseActionDefinition extends BaseJSONDefinition {
    static type: {
        ApplicationUpdate: string;
        BannerMessage: string;
        ChangeSet: string;
        ChangeUserPasscode: string;
        VerifyPasscode: string;
        CheckBarcodeScannerPrerequisite: string;
        CheckRequiredFields: string;
        ClearOfflineOData: string;
        CloseOfflineOData: string;
        ClosePage: string;
        CreateODataEntity: string;
        CreateODataMedia: string;
        CreateODataRelatedEntity: string;
        CreateODataRelatedMedia: string;
        CreateODataService: string;
        DeleteODataEntity: string;
        DeleteODataMedia: string;
        DownloadMediaOData: string;
        DownloadOfflineOData: string;
        DownloadStreamOData: string;
        Filter: string;
        InitializeOData: string;
        InitializeOfflineOData: string;
        LoggingLogMessage: string;
        LoggingSetLevel: string;
        LoggingSetState: string;
        LoggingUpload: string;
        Logout: string;
        Message: string;
        Navigation: string;
        ODataCallFunction: string;
        OpenBarcodeScanner: string;
        OpenDocument: string;
        OpenODataService: string;
        PopoverMenu: string;
        ProgressBanner: string;
        PushNotificationRegister: string;
        PushNotificationUnregister: string;
        ReadODataService: string;
        SendRequest: string;
        SetLanguage: string;
        SetRegion: string;
        SetTheme: string;
        ToastMessage: string;
        UndoPendingChanges: string;
        UpdateODataEntity: string;
        UploadOfflineOData: string;
        CancelUploadOfflineOData: string;
        CancelDownloadOfflineOData: string;
        UploadStreamOData: string;
    };
    constructor(path: string, data: any);
    readonly failureAction: string;
    readonly invalidAction: string;
    readonly successAction: string;
    readonly type: string;
    readonly validationRule: string;
    getOnSuccessLog(): LogDetail;
    getOnFailureLog(): LogDetail;
    getOnInvalidLog(): LogDetail;
    readonly showActivityIndicator: boolean;
    readonly activityIndicatorText: string;
    readonly actionResult: any;
}
export declare class LogDetail {
    private data;
    constructor(detailDefinition: any);
    getMessage(): string;
    getLevel(): string;
}
