{
	"_Type": "Action.Type.ODataService.CreateEntity",
	"Headers": {
    	"OfflineOData.NonMergeable": true
	},
	"Target":{
		"EntitySet": "PMMobileStatuses",
		"Service": "/SAPAssetManager/Services/AssetManager.service"
	},
	"Properties": {
		"NotifNum": "/SAPAssetManager/Rules/MobileStatus/MobileStatusLocalNotificationID.js",
		"MobileStatus": "/SAPAssetManager/Rules/MobileStatus/MobileStatusReceived.js",
		"ObjectType": "/SAPAssetManager/Rules/MobileStatus/MobileStatusNotificationObjectType.js",
		"ObjectKey": "/SAPAssetManager/Rules/MobileStatus/MobileStatusSetReceivedObjectKey.js",
        "EffectiveTimestamp": "/SAPAssetManager/Rules/DateTime/CurrentDateTime.js"
	},
	"CreateLinks": [{
        "Property": "NotifHeader_Nav",
        "Target": {
			"EntitySet" : "MyNotificationHeaders",
			"ReadLink": "/SAPAssetManager/Rules/MobileStatus/MobileStatusLocalNotificationReadLink.js"
        }
      }
	],
	"OnSuccess": "/SAPAssetManager/Rules/Common/ChangeSet/ChangeSetOnSuccess.js",
	"OnFailure" : "/SAPAssetManager/Rules/Common/ChangeSet/ChangeSetOnFailure.js",
	"ShowActivityIndicator": true,
	"ActivityIndicatorText" : " ",
	"ActionResult" : {"_Name" : "MobileStatusNotificationSetReceived"}
}
