import { Frame } from 'tns-core-modules/ui/frame';
import { MDKPage } from './MDKPage';
import { TabContentItem } from 'tns-core-modules/ui/bottom-navigation';
import { ExecuteSource } from '../common/ExecuteSource';
export declare class TabFrame extends Frame {
    private _parentPage;
    private _isActive;
    static isTab(frame: any): boolean;
    static isTopMostTab(): boolean;
    static isTabsTabFrame(frame: any): boolean;
    static isBottomNavigationTabFrame(frame: any): boolean;
    static getParentTopmostFrame(frame?: any): Frame;
    static isParentBottomNavigation(): boolean;
    static isChildBottomNavigation(frame: any): boolean;
    static isChildTabs(frame: any): boolean;
    static getTabControl(frame: any): any;
    static getTabTopmostFrame(includeTabs?: boolean): Frame;
    static getTabTopmostFrameByFrame(frame: any, includeTabs?: boolean): Frame;
    static getTabStrip(page: MDKPage): import("tns-core-modules/ui/bottom-navigation/bottom-navigation").TabStrip;
    static getCorrectTopmostFrame(source?: ExecuteSource, alwaysParentIfChildIsTabs?: boolean): any;
    static getBannerTopFrame(frame: any): any;
    private static _getStackLayout;
    static getTabs(parentPage: any): any;
    static getBottomNavigation(parentPage: any): boolean;
    static getTabsSelectedTabFrame(tabs: any): TabFrame;
    static getBottomNavSelectedTabFrame(bottomNav: any): TabFrame;
    static getTabPageFromTabItem(tabContentItem: TabContentItem): import("tns-core-modules/ui/frame/frame").Page;
    private static _getModalFrame;
    private static _hasModalFrame;
    private _initialPage;
    constructor(_parentPage: MDKPage, id?: string, _isActive?: boolean);
    onUnloaded(): void;
    parentPage: MDKPage;
    initialPage: MDKPage;
    readonly isActive: boolean;
    static getBannerAnchorLayout(frame: Frame): any;
    static isSideDrawerTabFrame(frame: any): boolean;
    static getSideDrawerSelectedTabFrame(tabs: any): TabFrame;
}
