// Generated by Apple Swift version 5.4 (swiftlang-1205.0.26.9 clang-1205.0.19.55)
#ifndef SAPMDC_SWIFT_H
#define SAPMDC_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreGraphics;
@import Foundation;
@import MessageUI;
@import ObjectiveC;
@import QuickLook;
@import SAPFiori;
@import UIKit;
#endif

#import <SAPMDC/SAPMDC.h>

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="SAPMDC",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

@class NSString;

SWIFT_CLASS_NAMED("ActivityIndicatorView")
@interface ActivityIndicatorViewSwift : NSObject
+ (void)dismiss;
+ (void)showWithParams:(NSDictionary<NSString *, id> * _Nonnull)params;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6SAPMDC12AnalyticCard")
@interface AnalyticCard : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSNumber;
@class FormCellItemDelegate;
@class NSArray;

SWIFT_CLASS("_TtC6SAPMDC11BaseSection")
@interface BaseSection : NSObject
- (void)redrawWithData:(NSDictionary * _Nonnull)data;
- (void)reloadRowWithIndex:(NSInteger)index;
- (void)updateRowWithIndex:(NSInteger)index data:(NSDictionary * _Nonnull)data;
- (void)reloadDataWithItemCount:(NSInteger)itemCount;
- (void)hideLazyLoadingIndicator;
- (void)refreshIndicators;
- (void)setIndicatorStateWithParams:(NSDictionary * _Nonnull)params;
- (void)setFormCellSectionItemWithParams:(NSDictionary<NSString *, id> * _Nonnull)params delegate:(FormCellItemDelegate * _Nonnull)delegate;
- (void)updateFormCellWithParams:(NSDictionary<NSString *, id> * _Nonnull)params row:(NSInteger)row;
- (void)updateFormCellsWithParams:(NSArray * _Nonnull)params;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC6SAPMDC29AnalyticCardCollectionSection")
@interface AnalyticCardCollectionSection : BaseSection
- (void)redrawWithData:(NSDictionary * _Nonnull)data;
@end


SWIFT_CLASS("_TtC6SAPMDC32AnalyticViewTapGestureRecogniser")
@interface AnalyticViewTapGestureRecogniser : UITapGestureRecognizer
- (nonnull instancetype)initWithTarget:(id _Nullable)target action:(SEL _Nullable)action OBJC_DESIGNATED_INITIALIZER;
@end

@class BannerDelegate;
@class UINavigationController;
@class UIView;

SWIFT_CLASS("_TtC6SAPMDC17BannerMessageView")
@interface BannerMessageView : NSObject
+ (void)displayWithParams:(NSDictionary<NSString *, id> * _Nonnull)params callback:(BannerDelegate * _Nonnull)callback;
+ (void)dismissBannerWithParams:(NSDictionary<NSString *, id> * _Nonnull)params;
+ (void)prepareToRelocate;
+ (void)relocateToNavigationController:(UINavigationController * _Nonnull)navigationController view:(UIView * _Nullable)view;
+ (void)updateTextWithParams:(NSDictionary<NSString *, id> * _Nonnull)params;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class BarcodeScannerDelegate;
@class NSBundle;
@class NSCoder;

SWIFT_CLASS("_TtC6SAPMDC28BarcodeScannerViewController")
@interface BarcodeScannerViewController : UIViewController
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) BarcodeScannerViewController * _Nonnull sharedInstance;)
+ (BarcodeScannerViewController * _Nonnull)sharedInstance SWIFT_WARN_UNUSED_RESULT;
///
- (void)create:(NSDictionary * _Nonnull)params callback:(BarcodeScannerDelegate * _Nonnull)callback;
///
- (void)check:(NSDictionary * _Nonnull)params callback:(BarcodeScannerDelegate * _Nonnull)callback;
/// :nodoc:
- (void)viewWillAppear:(BOOL)animated;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("BaseODataCruder")
@interface BaseODataCruder : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



SWIFT_CLASS("_TtC6SAPMDC16BaseTableSection")
@interface BaseTableSection : BaseSection
@end


SWIFT_CLASS("_TtC6SAPMDC13ButtonSection")
@interface ButtonSection : BaseSection
@end


SWIFT_CLASS("_TtC6SAPMDC12ChartContent")
@interface ChartContent : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS("_TtC6SAPMDC19ChartContentSection")
@interface ChartContentSection : BaseSection
@end


SWIFT_CLASS("_TtC6SAPMDC11ContactCell")
@interface ContactCell : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6SAPMDC18ContactCellSection")
@interface ContactCellSection : BaseTableSection
- (void)redrawWithData:(NSDictionary * _Nonnull)data;
- (void)updateRowWithIndex:(NSInteger)index data:(NSDictionary * _Nonnull)data;
@end

@class NSData;

/// Sends requests which can respond to OAuth challenges.
/// Uses SAPFoundation components and the SecureOAuth2TokenStore to accomplish this.
/// Requests may be triggered directly from Swift or from JavaScript.
/// The urlSession property may also be passed to other APIs to automatically handle authentication.
SWIFT_CLASS_NAMED("CpmsSession")
@interface CpmsSessionSwift : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) CpmsSessionSwift * _Nonnull sharedInstance;)
+ (CpmsSessionSwift * _Nonnull)sharedInstance SWIFT_WARN_UNUSED_RESULT;
+ (void)setSharedInstance:(CpmsSessionSwift * _Nonnull)value;
- (void)initializeWithParams:(NSDictionary * _Nonnull)params;
- (void)updateWithParams:(NSDictionary * _Nonnull)params;
- (void)sendRequestWithParams:(NSDictionary * _Nonnull)params resolve:(SnowblindPromiseResolveBlock _Nonnull)resolve reject:(SnowblindPromiseRejectBlock _Nonnull)reject;
- (NSData * _Nonnull)getFormDataWithBoundary:(NSString * _Nonnull)boundary params:(NSDictionary * _Nonnull)params SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("CrudParams")
@interface CrudParams : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSError;
@class ODataCreator;
@class ODataRelatedCreator;
@class ODataUpdater;
@class ODataDeleter;

SWIFT_PROTOCOL_NAMED("DataProvider")
@protocol DataProvider
/// Offline specific methods
- (void)downloadWithParams:(NSDictionary * _Nonnull)params success:(void (^ _Nonnull)(id _Nullable))success failure:(void (^ _Nonnull)(NSString * _Nullable, NSString * _Nullable, NSError * _Nullable))failure;
- (void)initOfflineStoreWithParams:(NSDictionary * _Nonnull)params success:(void (^ _Nonnull)(id _Nullable))success failure:(void (^ _Nonnull)(NSString * _Nullable, NSString * _Nullable, NSError * _Nullable))failure SWIFT_METHOD_FAMILY(none);
- (void)uploadWithParams:(NSDictionary * _Nonnull)params success:(void (^ _Nonnull)(id _Nullable))success failure:(void (^ _Nonnull)(NSString * _Nullable, NSString * _Nullable, NSError * _Nullable))failure;
- (void)cancelUploadWithParams:(NSDictionary * _Nonnull)params success:(void (^ _Nonnull)(id _Nullable))success failure:(void (^ _Nonnull)(NSString * _Nullable, NSString * _Nullable, NSError * _Nullable))failure;
- (void)cancelDownloadWithParams:(NSDictionary * _Nonnull)params success:(void (^ _Nonnull)(id _Nullable))success failure:(void (^ _Nonnull)(NSString * _Nullable, NSString * _Nullable, NSError * _Nullable))failure;
- (void)closeWithParams:(NSDictionary * _Nonnull)params success:(SWIFT_NOESCAPE void (^ _Nonnull)(id _Nullable))success failure:(SWIFT_NOESCAPE void (^ _Nonnull)(NSString * _Nullable, NSString * _Nullable, NSError * _Nullable))failure;
- (void)clearWithParams:(NSDictionary * _Nonnull)params success:(SWIFT_NOESCAPE void (^ _Nonnull)(id _Nullable))success failure:(SWIFT_NOESCAPE void (^ _Nonnull)(NSString * _Nullable, NSString * _Nullable, NSError * _Nullable))failure;
/// Online specific methods
- (void)createWithParams:(NSDictionary * _Nonnull)params success:(void (^ _Nonnull)(id _Nullable))success failure:(void (^ _Nonnull)(NSString * _Nullable, NSString * _Nullable, NSError * _Nullable))failure;
- (void)openWithParams:(NSDictionary * _Nonnull)params success:(void (^ _Nonnull)(id _Nullable))success failure:(void (^ _Nonnull)(NSString * _Nullable, NSString * _Nullable, NSError * _Nullable))failure;
/// Common CRUD methods
- (void)readWithEntitySet:(NSString * _Nonnull)entitySet properties:(NSArray * _Nonnull)properties queryString:(NSString * _Nullable)queryString headers:(NSDictionary * _Nullable)headers options:(NSDictionary * _Nullable)options pageSize:(NSNumber * _Nullable)pageSize success:(void (^ _Nonnull)(id _Nullable))success failure:(void (^ _Nonnull)(NSString * _Nullable, NSString * _Nullable, NSError * _Nullable))failure;
- (BOOL)createEntityWithOdataCreator:(ODataCreator * _Nonnull)odataCreator error:(NSError * _Nullable * _Nullable)error success:(void (^ _Nonnull)(id _Nullable))success failure:(void (^ _Nonnull)(NSString * _Nullable, NSString * _Nullable, NSError * _Nullable))failure;
- (BOOL)createRelatedEntityWithOdataCreator:(ODataRelatedCreator * _Nonnull)odataCreator error:(NSError * _Nullable * _Nullable)error success:(void (^ _Nonnull)(id _Nullable))success failure:(void (^ _Nonnull)(NSString * _Nullable, NSString * _Nullable, NSError * _Nullable))failure;
- (BOOL)updateEntityWithOdataUpdater:(ODataUpdater * _Nonnull)odataUpdater error:(NSError * _Nullable * _Nullable)error success:(void (^ _Nonnull)(id _Nullable))success failure:(void (^ _Nonnull)(NSString * _Nullable, NSString * _Nullable, NSError * _Nullable))failure;
- (BOOL)deleteEntityWithOdataDeleter:(ODataDeleter * _Nonnull)odataDeleter error:(NSError * _Nullable * _Nullable)error success:(void (^ _Nonnull)(id _Nullable))success failure:(void (^ _Nonnull)(NSString * _Nullable, NSString * _Nullable, NSError * _Nullable))failure;
- (BOOL)deleteMediaEntityWithEntitySetName:(NSString * _Nonnull)entitySetName queryString:(NSString * _Nullable)queryString readLink:(NSString * _Nullable)readLink headers:(NSDictionary * _Nullable)headers options:(NSDictionary * _Nullable)options error:(NSError * _Nullable * _Nullable)error success:(void (^ _Nonnull)(id _Nullable))success failure:(void (^ _Nonnull)(NSString * _Nullable, NSString * _Nullable, NSError * _Nullable))failure;
- (void)createMediaEntityWithEntitySetName:(NSString * _Nonnull)entitySetName properties:(NSDictionary * _Nonnull)properties headers:(NSDictionary * _Nullable)headers options:(NSDictionary * _Nullable)options media:(NSArray * _Nonnull)media success:(void (^ _Nonnull)(id _Nullable))success failure:(void (^ _Nonnull)(NSString * _Nullable, NSString * _Nullable, NSError * _Nullable))failure;
- (void)createMediaEntity1WithEntitySetName:(NSString * _Nonnull)entitySetName properties:(NSDictionary * _Nonnull)properties headers:(NSDictionary * _Nullable)headers media:(NSArray * _Nonnull)media success:(void (^ _Nonnull)(id _Nullable))success failure:(void (^ _Nonnull)(NSString * _Nullable, NSString * _Nullable, NSError * _Nullable))failure;
- (void)createRelatedMediaEntityWithEntitySetName:(NSString * _Nonnull)entitySetName properties:(NSDictionary * _Nonnull)properties parent:(NSDictionary * _Nonnull)parent headers:(NSDictionary * _Nullable)headers options:(NSDictionary * _Nullable)options media:(NSArray * _Nonnull)media success:(void (^ _Nonnull)(id _Nullable))success failure:(void (^ _Nonnull)(NSString * _Nullable, NSString * _Nullable, NSError * _Nullable))failure;
- (void)downloadMediaWithEntitySetName:(NSString * _Nonnull)entitySetName queryString:(NSString * _Nullable)queryString readLink:(NSString * _Nullable)readLink headers:(NSDictionary * _Nullable)headers options:(NSDictionary * _Nullable)options success:(void (^ _Nonnull)(id _Nullable))success failure:(void (^ _Nonnull)(NSString * _Nullable, NSString * _Nullable, NSError * _Nullable))failure;
- (void)isMediaLocalWithEntitySetName:(NSString * _Nonnull)entitySetName readLink:(NSString * _Nullable)readLink success:(void (^ _Nonnull)(id _Nullable))success failure:(void (^ _Nonnull)(NSString * _Nullable, NSString * _Nullable, NSError * _Nullable))failure;
- (void)beginChangeSetWithSuccess:(void (^ _Nonnull)(id _Nullable))success failure:(void (^ _Nonnull)(NSString * _Nullable, NSString * _Nullable, NSError * _Nullable))failure;
- (void)cancelChangeSetWithSuccess:(void (^ _Nonnull)(id _Nullable))success failure:(void (^ _Nonnull)(NSString * _Nullable, NSString * _Nullable, NSError * _Nullable))failure;
- (void)commitChangeSetWithSuccess:(void (^ _Nonnull)(id _Nullable))success failure:(void (^ _Nonnull)(NSString * _Nullable, NSString * _Nullable, NSError * _Nullable))failure;
- (void)countWithEntitySet:(NSString * _Nonnull)entitySet properties:(NSArray * _Nonnull)properties queryString:(NSString * _Nullable)queryString headers:(NSDictionary * _Nullable)headers options:(NSDictionary * _Nullable)options success:(void (^ _Nonnull)(id _Nullable))success failure:(void (^ _Nonnull)(NSString * _Nullable, NSString * _Nullable, NSError * _Nullable))failure;
- (void)callFunctionWithFunctionName:(NSString * _Nonnull)functionName parameters:(NSDictionary * _Nonnull)parameters headers:(NSDictionary * _Nonnull)headers options:(NSDictionary * _Nonnull)options success:(void (^ _Nonnull)(id _Nullable))success failure:(void (^ _Nonnull)(NSString * _Nullable, NSString * _Nullable, NSError * _Nullable))failure;
- (void)downloadStreamWithEntitySetName:(NSString * _Nonnull)entitySetName properties:(NSArray<NSString *> * _Nonnull)properties queryString:(NSString * _Nullable)queryString readLink:(NSString * _Nullable)readLink headers:(NSDictionary * _Nullable)headers options:(NSDictionary * _Nullable)options success:(void (^ _Nonnull)(id _Nullable))success failure:(void (^ _Nonnull)(NSString * _Nullable, NSString * _Nullable, NSError * _Nullable))failure;
- (void)uploadStreamWithEntitySetName:(NSString * _Nonnull)entitySetName properties:(NSDictionary * _Nonnull)properties queryString:(NSString * _Nullable)queryString readLink:(NSString * _Nullable)readLink headers:(NSDictionary * _Nullable)headers options:(NSDictionary * _Nullable)options success:(void (^ _Nonnull)(id _Nullable))success failure:(void (^ _Nonnull)(NSString * _Nullable, NSString * _Nullable, NSError * _Nullable))failure;
- (NSString * _Nonnull)getPropertyTypeWithEntitySetName:(NSString * _Nonnull)entitySetName propertyName:(NSString * _Nonnull)propertyName SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)getVersion SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getOfflineStoreStatus SWIFT_WARN_UNUSED_RESULT;
- (id _Nullable)undoPendingChangesWithEntitySetName:(NSString * _Nonnull)entitySetName queryString:(NSString * _Nullable)queryString editLink:(NSString * _Nullable)editLink error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (id _Nullable)getOfflineParameterWithName:(NSString * _Nonnull)name error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (void)setOfflineParameterWithName:(NSString * _Nonnull)name value:(id _Nonnull)value;
@end


SWIFT_CLASS_NAMED("DataServiceManager")
@interface DataServiceManager : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) DataServiceManager * _Nonnull sharedInstance;)
+ (DataServiceManager * _Nonnull)sharedInstance SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (void)downloadWithParams:(NSDictionary * _Nonnull)params resolve:(SnowblindPromiseResolveBlock _Nonnull)resolve reject:(SnowblindPromiseRejectBlock _Nonnull)reject;
- (void)initOfflineStoreWithParams:(NSDictionary * _Nonnull)params resolve:(SnowblindPromiseResolveBlock _Nonnull)resolve reject:(SnowblindPromiseRejectBlock _Nonnull)reject SWIFT_METHOD_FAMILY(none);
- (void)closeWithParams:(NSDictionary * _Nonnull)params resolve:(SnowblindPromiseResolveBlock _Nonnull)resolve reject:(SnowblindPromiseRejectBlock _Nonnull)reject;
- (void)clearWithParams:(NSDictionary * _Nonnull)params resolve:(SnowblindPromiseResolveBlock _Nonnull)resolve reject:(SnowblindPromiseRejectBlock _Nonnull)reject;
- (void)uploadWithParams:(NSDictionary * _Nonnull)params resolve:(SnowblindPromiseResolveBlock _Nonnull)resolve reject:(SnowblindPromiseRejectBlock _Nonnull)reject;
- (void)cancelUploadWithParams:(NSDictionary * _Nonnull)params resolve:(SnowblindPromiseResolveBlock _Nonnull)resolve reject:(SnowblindPromiseRejectBlock _Nonnull)reject;
- (void)cancelDownloadWithParams:(NSDictionary * _Nonnull)params resolve:(SnowblindPromiseResolveBlock _Nonnull)resolve reject:(SnowblindPromiseRejectBlock _Nonnull)reject;
- (void)createWithParams:(NSDictionary * _Nonnull)params resolve:(SnowblindPromiseResolveBlock _Nonnull)resolve reject:(SnowblindPromiseRejectBlock _Nonnull)reject;
- (void)openWithParams:(NSDictionary * _Nonnull)params resolve:(SnowblindPromiseResolveBlock _Nonnull)resolve reject:(SnowblindPromiseRejectBlock _Nonnull)reject;
- (void)readWithParams:(NSDictionary * _Nonnull)params resolve:(SnowblindPromiseResolveBlock _Nonnull)resolve reject:(SnowblindPromiseRejectBlock _Nonnull)reject;
- (void)createEntityWithParams:(NSDictionary * _Nonnull)params resolve:(SnowblindPromiseResolveBlock _Nonnull)resolve reject:(SnowblindPromiseRejectBlock _Nonnull)reject;
- (void)createRelatedEntityWithParams:(NSDictionary * _Nonnull)params resolve:(SnowblindPromiseResolveBlock _Nonnull)resolve reject:(SnowblindPromiseRejectBlock _Nonnull)reject;
- (void)updateWithParams:(NSDictionary * _Nonnull)params resolve:(SnowblindPromiseResolveBlock _Nonnull)resolve reject:(SnowblindPromiseRejectBlock _Nonnull)reject;
- (void)deleteEntityWithParams:(NSDictionary * _Nonnull)params resolve:(SnowblindPromiseResolveBlock _Nonnull)resolve reject:(SnowblindPromiseRejectBlock _Nonnull)reject;
- (void)createMediaWithParams:(NSDictionary * _Nonnull)params resolve:(SnowblindPromiseResolveBlock _Nonnull)resolve reject:(SnowblindPromiseRejectBlock _Nonnull)reject;
- (void)createRelatedMediaWithParams:(NSDictionary * _Nonnull)params resolve:(SnowblindPromiseResolveBlock _Nonnull)resolve reject:(SnowblindPromiseRejectBlock _Nonnull)reject;
- (void)beginChangeSetWithParams:(NSDictionary * _Nonnull)params resolve:(SnowblindPromiseResolveBlock _Nonnull)resolve reject:(SnowblindPromiseRejectBlock _Nonnull)reject;
- (void)cancelChangeSetWithParams:(NSDictionary * _Nonnull)params resolve:(SnowblindPromiseResolveBlock _Nonnull)resolve reject:(SnowblindPromiseRejectBlock _Nonnull)reject;
- (void)commitChangeSetWithParams:(NSDictionary * _Nonnull)params resolve:(SnowblindPromiseResolveBlock _Nonnull)resolve reject:(SnowblindPromiseRejectBlock _Nonnull)reject;
- (void)deleteMediaWithParams:(NSDictionary * _Nonnull)params resolve:(SnowblindPromiseResolveBlock _Nonnull)resolve reject:(SnowblindPromiseRejectBlock _Nonnull)reject;
- (void)downloadMediaWithParams:(NSDictionary * _Nonnull)params resolve:(SnowblindPromiseResolveBlock _Nonnull)resolve reject:(SnowblindPromiseRejectBlock _Nonnull)reject;
- (void)isMediaLocalWithParams:(NSDictionary * _Nonnull)params resolve:(SnowblindPromiseResolveBlock _Nonnull)resolve reject:(SnowblindPromiseRejectBlock _Nonnull)reject;
- (void)countWithParams:(NSDictionary * _Nonnull)params resolve:(SnowblindPromiseResolveBlock _Nonnull)resolve reject:(SnowblindPromiseRejectBlock _Nonnull)reject;
- (void)callFunctionWithParams:(NSDictionary * _Nonnull)params resolve:(SnowblindPromiseResolveBlock _Nonnull)resolve reject:(SnowblindPromiseRejectBlock _Nonnull)reject;
- (void)downloadStreamWithParams:(NSDictionary * _Nonnull)params resolve:(SnowblindPromiseResolveBlock _Nonnull)resolve reject:(SnowblindPromiseRejectBlock _Nonnull)reject;
- (void)uploadStreamWithParams:(NSDictionary * _Nonnull)params resolve:(SnowblindPromiseResolveBlock _Nonnull)resolve reject:(SnowblindPromiseRejectBlock _Nonnull)reject;
- (void)base64StringToBinaryWithParams:(NSString * _Nonnull)params resolve:(SnowblindPromiseResolveBlock _Nonnull)resolve reject:(SnowblindPromiseRejectBlock _Nonnull)reject;
- (NSString * _Nonnull)getPropertyTypeWithParams:(NSDictionary * _Nonnull)params SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)getVersionWithParams:(NSDictionary * _Nonnull)params SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getOfflineStoreStatusWithParams:(NSDictionary * _Nonnull)params SWIFT_WARN_UNUSED_RESULT;
- (id _Nonnull)getOfflineParameterWithParams:(NSDictionary * _Nonnull)params SWIFT_WARN_UNUSED_RESULT;
- (void)setOfflineParameterWithParams:(NSDictionary * _Nonnull)params;
- (void)undoPendingChangesWithParams:(NSDictionary * _Nonnull)params resolve:(SnowblindPromiseResolveBlock _Nonnull)resolve reject:(SnowblindPromiseRejectBlock _Nonnull)reject;
@end


SWIFT_CLASS("_TtC6SAPMDC16ExtensionSection")
@interface ExtensionSection : BaseSection
@end

@class UITableView;
@class UITableViewCell;

SWIFT_PROTOCOL("_TtP6SAPMDC29ExtensionTableViewCellHandler_")
@protocol ExtensionTableViewCellHandler
- (NSString * _Nonnull)getReuseIdentifier SWIFT_WARN_UNUSED_RESULT;
- (void)registerCellTo:(UITableView * _Nonnull)tableView;
- (void)configureReusableCell:(UITableViewCell * _Nonnull)tableViewCell;
@end



/// Subclass of <code>FUIButton</code> to store additional information, which are needed to carry out the touch event.
SWIFT_RESILIENT_CLASS("_TtC6SAPMDC16FUIButtonWrapper")
@interface FUIButtonWrapper : FUIButton
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end


@class NSIndexPath;
@class UITextField;

SWIFT_RESILIENT_CLASS("_TtC6SAPMDC31FormCellContainerViewController")
@interface FormCellContainerViewController : FUIFormTableViewController <UITextFieldDelegate>
@property (nonatomic) NSInteger numberOfSections;
@property (nonatomic, copy) NSArray<NSNumber *> * _Nonnull numberOfRowsInSection;
@property (nonatomic, copy) NSArray<NSString *> * _Nonnull sectionNames;
@property (nonatomic) BOOL isInPopover;
@property (nonatomic, strong) UITableView * _Nullable tableViewForExtension;
@property (nonatomic, strong) UITableViewCell * _Nullable tableViewCellForExtension;
@property (nonatomic) BOOL isInEmbeddedFrame;
- (void)viewDidLoad;
- (void)viewDidAppear:(BOOL)animated;
- (void)viewWillDisappear:(BOOL)animated;
- (NSInteger)numberOfSectionsInTableView:(UITableView * _Nonnull)tableView SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForHeaderInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UIView * _Nullable)tableView:(UITableView * _Nonnull)tableView viewForHeaderInSection:(NSInteger)sectionIndex SWIFT_WARN_UNUSED_RESULT;
- (UIView * _Nullable)tableView:(UITableView * _Nonnull)tableView viewForFooterInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForFooterInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (void)addFormCell:(NSDictionary<NSString *, id> * _Nonnull)params withDelegate:(FormCellItemDelegate * _Nonnull)delegate;
- (void)updateFormCell:(NSDictionary<NSString *, id> * _Nonnull)params cellRow:(NSInteger)row cellSection:(NSInteger)section;
/// Update form cell with an array of udpated formCell values.
/// @param params The NSArray* which contains NSDictionary that stores formCell property values
/// @param style The NUI style class for the container
- (void)updateFormCells:(NSArray * _Nonnull)params withStyle:(NSString * _Nullable)style;
- (void)setLocale:(NSString * _Nonnull)locale;
- (void)setFocus:(NSInteger)row cellSection:(NSInteger)section;
- (void)hideLazyLoadingIndicator:(NSInteger)row cellSection:(NSInteger)section;
- (BOOL)textField:(UITextField * _Nonnull)textField shouldChangeCharactersInRange:(NSRange)range replacementString:(NSString * _Nonnull)string SWIFT_WARN_UNUSED_RESULT;
- (BOOL)textFieldShouldReturn:(UITextField * _Nonnull)textField SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithStyle:(UITableViewStyle)style OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6SAPMDC15FormCellSection")
@interface FormCellSection : BaseSection <UITextFieldDelegate>
@property (nonatomic, strong) UITableView * _Nullable tableViewForExtension;
@property (nonatomic, strong) UITableViewCell * _Nullable tableViewCellForExtension;
- (void)redrawWithData:(NSDictionary * _Nonnull)data;
- (void)setFormCellSectionItemWithParams:(NSDictionary<NSString *, id> * _Nonnull)params delegate:(FormCellItemDelegate * _Nonnull)delegate;
- (void)updateFormCellWithParams:(NSDictionary<NSString *, id> * _Nonnull)params row:(NSInteger)row;
- (void)hideLazyLoadingIndicatorWithRow:(NSInteger)row;
- (void)updateFormCellsWithParams:(NSArray * _Nonnull)params;
- (void)setFocusWithRow:(NSInteger)row;
- (BOOL)textField:(UITextField * _Nonnull)textField shouldChangeCharactersInRange:(NSRange)range replacementString:(NSString * _Nonnull)string SWIFT_WARN_UNUSED_RESULT;
- (BOOL)textFieldShouldReturn:(UITextField * _Nonnull)textField SWIFT_WARN_UNUSED_RESULT;
@end



SWIFT_CLASS("_TtC6SAPMDC16GridTableSection")
@interface GridTableSection : BaseTableSection
- (void)redrawWithData:(NSDictionary * _Nonnull)data;
- (void)updateRowWithIndex:(NSInteger)index data:(NSDictionary * _Nonnull)data;
@end


SWIFT_CLASS("_TtC6SAPMDC22ImageCollectionSection")
@interface ImageCollectionSection : BaseSection
@end


/// <code>UITableViewCell</code> containing a <code>UICollectionView</code>.
/// Takes responsibility for correct layout and sizing for the items, for different screen dimensions.
SWIFT_RESILIENT_CLASS("_TtC6SAPMDC36ImageItemCollectionViewTableViewCell")
@interface ImageItemCollectionViewTableViewCell : FUIBaseCollectionViewTableViewCell
/// :nodoc:
- (void)layoutSubviews;
/// :nodoc:
- (void)layoutMarginsDidChange;
/// :nodoc:
- (void)prepareForReuse;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6SAPMDC9KPIHeader")
@interface KPIHeader : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6SAPMDC16KPIHeaderSection")
@interface KPIHeaderSection : BaseSection
- (void)redrawWithData:(NSDictionary * _Nonnull)data;
- (void)reloadDataWithItemCount:(NSInteger)itemCount;
- (void)reloadRowWithIndex:(NSInteger)index;
@end


SWIFT_CLASS("_TtC6SAPMDC10KPISection")
@interface KPISection : KPIHeaderSection
@end


SWIFT_CLASS("_TtC6SAPMDC15KeyValueSection")
@interface KeyValueSection : BaseSection
@end

@protocol FUIListPicker;
@class NSTimer;
@class UISearchBar;

SWIFT_CLASS("_TtC6SAPMDC20ListPickerDataSource")
@interface ListPickerDataSource : NSObject <FUIListPickerDataSource, FUIListPickerSearchResultsUpdating, UISearchBarDelegate>
- (NSInteger)numberOfRowsIn:(UITableView * _Nonnull)listPickerTableView SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)listPickerTableView:(UITableView * _Nonnull)tableView cellForRowAt:(NSInteger)index isFiltered:(BOOL)isFiltered SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)listPickerTableView:(UITableView * _Nonnull)tableView cellForItemWithUniqueIdentifier:(NSString * _Nonnull)uniqueIdentifier SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)listPickerTableView:(UITableView * _Nonnull)tableView uniqueIdentifierForItemAt:(NSInteger)index SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)listPickerTableView:(UITableView * _Nonnull)tableView indexForUniqueIdentifier:(NSString * _Nonnull)uniqueIdentifier SWIFT_WARN_UNUSED_RESULT;
- (void)listPicker:(id <FUIListPicker> _Nonnull)listPicker updateSearchResults:(NSString * _Nonnull)forSearchString;
- (void)callSearchCallbackWithSender:(NSTimer * _Nonnull)sender;
- (void)searchBarSearchButtonClicked:(UISearchBar * _Nonnull)searchBar;
- (BOOL)listPicker:(id <FUIListPicker> _Nonnull)listPicker filteredDataSourceContainsItemWithUniqueIdentifier:(NSString * _Nonnull)uniqueIdentifier SWIFT_WARN_UNUSED_RESULT;
- (BOOL)listPicker:(id <FUIListPicker> _Nonnull)listPicker filteredDataSourceContainsItemAt:(NSInteger)unfilteredIndex SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)listPicker:(id <FUIListPicker> _Nonnull)listPicker unfilteredDataSourceIndexOfItemAt:(NSInteger)filteredIndex SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("LoggerManager")
@interface LoggerManagerSwift : NSObject
+ (BOOL)attachUploaderToRootLoggerWithMaxFileSize:(NSInteger)maxFileSizeInMegaBytes error:(NSError * _Nullable * _Nullable)error;
+ (void)uploadLogsWithBackendURL:(NSString * _Nonnull)backendURL applicationID:(NSString * _Nullable)applicationID resolve:(SnowblindPromiseResolveBlock _Nonnull)resolve reject:(SnowblindPromiseRejectBlock _Nonnull)reject;
+ (BOOL)addLocalFileHandlerWithFileName:(NSString * _Nonnull)fileName maxFileSize:(NSInteger)maxFileSizeInMegaBytes error:(NSError * _Nullable * _Nullable)error;
+ (void)activateLogLevelWithSeverity:(NSString * _Nonnull)level;
+ (void)log:(NSString * _Nonnull)message withSeverity:(NSString * _Nullable)severity;
+ (BOOL)clearLogAndReturnError:(NSError * _Nullable * _Nullable)error;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@protocol SwiftExtensionDelegate;

SWIFT_PROTOCOL("_TtP6SAPMDC12MDKExtension_")
@protocol MDKExtension
@property (nonatomic, strong) id <SwiftExtensionDelegate> _Nullable delegate;
- (void)updateWith:(NSDictionary * _Nonnull)params;
- (void)controlValueChangedWith:(NSDictionary * _Nonnull)binding;
@end


/// Get SAP Passport value for HTTP Request Header.
/// Uses SAPFoundation network observer to accomplish this.
/// Requests may be triggered directly from Swift or from JavaScript.
SWIFT_CLASS("_TtC6SAPMDC11MDKPassport")
@interface MDKPassport : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) MDKPassport * _Nonnull sharedInstance;)
+ (MDKPassport * _Nonnull)sharedInstance SWIFT_WARN_UNUSED_RESULT;
+ (void)setSharedInstance:(MDKPassport * _Nonnull)value;
- (NSString * _Nonnull)getHeaderValueWithParams:(NSDictionary * _Nonnull)params SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@protocol UIViewControllerTransitionCoordinator;

SWIFT_CLASS_NAMED("MissingExtensionPlaceholder")
@interface MissingExtensionPlaceholder : UIViewController <MDKExtension>
@property (nonatomic, strong) id <SwiftExtensionDelegate> _Nullable delegate;
- (void)controlValueChangedWith:(NSDictionary * _Nonnull)value;
- (void)updateWith:(NSDictionary * _Nonnull)params;
@property (nonatomic, copy) NSString * _Nonnull className;
- (void)viewDidLoad;
- (void)viewWillTransitionToSize:(CGSize)size withTransitionCoordinator:(id <UIViewControllerTransitionCoordinator> _Nonnull)coordinator;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS_NAMED("NavigationBar")
@interface NavigationBarSwift : NSObject
+ (void)applyFioriStyle;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("ODataCreator")
@interface ODataCreator : BaseODataCruder
@end


SWIFT_CLASS_NAMED("ODataDeleter")
@interface ODataDeleter : BaseODataCruder
@end


SWIFT_CLASS_NAMED("ODataLinker")
@interface ODataLinker : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("ODataLinkCreator")
@interface ODataLinkCreator : ODataLinker
@end


SWIFT_CLASS_NAMED("ODataLinkDeleter")
@interface ODataLinkDeleter : ODataLinker
@end


SWIFT_CLASS_NAMED("ODataLinkUpdater")
@interface ODataLinkUpdater : ODataLinkCreator
@end



SWIFT_CLASS_NAMED("ODataRelatedCreator")
@interface ODataRelatedCreator : BaseODataCruder
@end


SWIFT_CLASS_NAMED("ODataServiceProvider")
@interface ODataServiceProvider : NSObject <DataProvider>
- (void)openWithParams:(NSDictionary * _Nonnull)params success:(void (^ _Nonnull)(id _Nullable))success failure:(void (^ _Nonnull)(NSString * _Nullable, NSString * _Nullable, NSError * _Nullable))failure;
- (void)initOfflineStoreWithParams:(NSDictionary * _Nonnull)params success:(void (^ _Nonnull)(id _Nullable))success failure:(void (^ _Nonnull)(NSString * _Nullable, NSString * _Nullable, NSError * _Nullable))failure SWIFT_METHOD_FAMILY(none);
- (void)closeWithParams:(NSDictionary * _Nonnull)params success:(SWIFT_NOESCAPE void (^ _Nonnull)(id _Nullable))success failure:(SWIFT_NOESCAPE void (^ _Nonnull)(NSString * _Nullable, NSString * _Nullable, NSError * _Nullable))failure;
- (void)clearWithParams:(NSDictionary * _Nonnull)params success:(SWIFT_NOESCAPE void (^ _Nonnull)(id _Nullable))success failure:(SWIFT_NOESCAPE void (^ _Nonnull)(NSString * _Nullable, NSString * _Nullable, NSError * _Nullable))failure;
- (void)uploadWithParams:(NSDictionary * _Nonnull)params success:(void (^ _Nonnull)(id _Nullable))success failure:(void (^ _Nonnull)(NSString * _Nullable, NSString * _Nullable, NSError * _Nullable))failure;
- (void)downloadWithParams:(NSDictionary * _Nonnull)params success:(void (^ _Nonnull)(id _Nullable))success failure:(void (^ _Nonnull)(NSString * _Nullable, NSString * _Nullable, NSError * _Nullable))failure;
- (void)cancelUploadWithParams:(NSDictionary * _Nonnull)params success:(SWIFT_NOESCAPE void (^ _Nonnull)(id _Nullable))success failure:(SWIFT_NOESCAPE void (^ _Nonnull)(NSString * _Nullable, NSString * _Nullable, NSError * _Nullable))failure;
- (void)cancelDownloadWithParams:(NSDictionary * _Nonnull)params success:(SWIFT_NOESCAPE void (^ _Nonnull)(id _Nullable))success failure:(SWIFT_NOESCAPE void (^ _Nonnull)(NSString * _Nullable, NSString * _Nullable, NSError * _Nullable))failure;
- (void)downloadMediaWithEntitySetName:(NSString * _Nonnull)entitySetName queryString:(NSString * _Nullable)queryString readLink:(NSString * _Nullable)readLink headers:(NSDictionary * _Nullable)headers options:(NSDictionary * _Nullable)options success:(void (^ _Nonnull)(id _Nullable))success failure:(void (^ _Nonnull)(NSString * _Nullable, NSString * _Nullable, NSError * _Nullable))failure;
- (void)isMediaLocalWithEntitySetName:(NSString * _Nonnull)entitySetName readLink:(NSString * _Nullable)readLink success:(void (^ _Nonnull)(id _Nullable))success failure:(void (^ _Nonnull)(NSString * _Nullable, NSString * _Nullable, NSError * _Nullable))failure;
- (void)createWithParams:(NSDictionary * _Nonnull)params success:(void (^ _Nonnull)(id _Nullable))success failure:(void (^ _Nonnull)(NSString * _Nullable, NSString * _Nullable, NSError * _Nullable))failure;
- (void)readWithEntitySet:(NSString * _Nonnull)entity properties:(NSArray * _Nonnull)properties queryString:(NSString * _Nullable)queryString headers:(NSDictionary * _Nullable)headers options:(NSDictionary * _Nullable)options pageSize:(NSNumber * _Nullable)pageSize success:(void (^ _Nonnull)(id _Nullable))success failure:(void (^ _Nonnull)(NSString * _Nullable, NSString * _Nullable, NSError * _Nullable))failure;
- (BOOL)createEntityWithOdataCreator:(ODataCreator * _Nonnull)odataCreator error:(NSError * _Nullable * _Nullable)error success:(void (^ _Nonnull)(id _Nullable))success failure:(void (^ _Nonnull)(NSString * _Nullable, NSString * _Nullable, NSError * _Nullable))failure;
- (BOOL)createRelatedEntityWithOdataCreator:(ODataRelatedCreator * _Nonnull)odataCreator error:(NSError * _Nullable * _Nullable)error success:(void (^ _Nonnull)(id _Nullable))success failure:(void (^ _Nonnull)(NSString * _Nullable, NSString * _Nullable, NSError * _Nullable))failure;
- (BOOL)updateEntityWithOdataUpdater:(ODataUpdater * _Nonnull)odataUpdater error:(NSError * _Nullable * _Nullable)error success:(void (^ _Nonnull)(id _Nullable))success failure:(void (^ _Nonnull)(NSString * _Nullable, NSString * _Nullable, NSError * _Nullable))failure;
- (BOOL)deleteEntityWithOdataDeleter:(ODataDeleter * _Nonnull)odataDeleter error:(NSError * _Nullable * _Nullable)error success:(void (^ _Nonnull)(id _Nullable))success failure:(void (^ _Nonnull)(NSString * _Nullable, NSString * _Nullable, NSError * _Nullable))failure;
- (BOOL)deleteMediaEntityWithEntitySetName:(NSString * _Nonnull)entitySetName queryString:(NSString * _Nullable)queryString readLink:(NSString * _Nullable)readLink headers:(NSDictionary * _Nullable)headers options:(NSDictionary * _Nullable)options error:(NSError * _Nullable * _Nullable)error success:(void (^ _Nonnull)(id _Nullable))success failure:(void (^ _Nonnull)(NSString * _Nullable, NSString * _Nullable, NSError * _Nullable))failure;
- (id _Nullable)undoPendingChangesWithEntitySetName:(NSString * _Nonnull)entitySetName queryString:(NSString * _Nullable)queryString editLink:(NSString * _Nullable)editLink error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (void)downloadStreamWithEntitySetName:(NSString * _Nonnull)entitySetName properties:(NSArray<NSString *> * _Nonnull)properties queryString:(NSString * _Nullable)queryString readLink:(NSString * _Nullable)readLink headers:(NSDictionary * _Nullable)headers options:(NSDictionary * _Nullable)options success:(void (^ _Nonnull)(id _Nullable))success failure:(void (^ _Nonnull)(NSString * _Nullable, NSString * _Nullable, NSError * _Nullable))failure;
- (void)uploadStreamWithEntitySetName:(NSString * _Nonnull)entitySetName properties:(NSDictionary * _Nonnull)properties queryString:(NSString * _Nullable)queryString readLink:(NSString * _Nullable)readLink headers:(NSDictionary * _Nullable)headers options:(NSDictionary * _Nullable)options success:(void (^ _Nonnull)(id _Nullable))success failure:(void (^ _Nonnull)(NSString * _Nullable, NSString * _Nullable, NSError * _Nullable))failure;
- (void)createMediaEntityWithEntitySetName:(NSString * _Nonnull)entitySetName properties:(NSDictionary * _Nonnull)properties headers:(NSDictionary * _Nullable)headers options:(NSDictionary * _Nullable)options media:(NSArray * _Nonnull)media success:(void (^ _Nonnull)(id _Nullable))success failure:(void (^ _Nonnull)(NSString * _Nullable, NSString * _Nullable, NSError * _Nullable))failure;
- (void)createMediaEntity1WithEntitySetName:(NSString * _Nonnull)entitySetName properties:(NSDictionary * _Nonnull)properties headers:(NSDictionary * _Nullable)headers media:(NSArray * _Nonnull)media success:(void (^ _Nonnull)(id _Nullable))success failure:(void (^ _Nonnull)(NSString * _Nullable, NSString * _Nullable, NSError * _Nullable))failure;
- (void)createRelatedMediaEntityWithEntitySetName:(NSString * _Nonnull)entitySetName properties:(NSDictionary * _Nonnull)properties parent:(NSDictionary * _Nonnull)parent headers:(NSDictionary * _Nullable)headers options:(NSDictionary * _Nullable)options media:(NSArray * _Nonnull)media success:(void (^ _Nonnull)(id _Nullable))success failure:(void (^ _Nonnull)(NSString * _Nullable, NSString * _Nullable, NSError * _Nullable))failure;
- (void)beginChangeSetWithSuccess:(void (^ _Nonnull)(id _Nullable))success failure:(void (^ _Nonnull)(NSString * _Nullable, NSString * _Nullable, NSError * _Nullable))failure;
- (void)cancelChangeSetWithSuccess:(void (^ _Nonnull)(id _Nullable))success failure:(void (^ _Nonnull)(NSString * _Nullable, NSString * _Nullable, NSError * _Nullable))failure;
- (void)commitChangeSetWithSuccess:(void (^ _Nonnull)(id _Nullable))success failure:(void (^ _Nonnull)(NSString * _Nullable, NSString * _Nullable, NSError * _Nullable))failure;
- (void)countWithEntitySet:(NSString * _Nonnull)entity properties:(NSArray * _Nonnull)properties queryString:(NSString * _Nullable)queryString headers:(NSDictionary * _Nullable)headers options:(NSDictionary * _Nullable)options success:(void (^ _Nonnull)(id _Nullable))success failure:(void (^ _Nonnull)(NSString * _Nullable, NSString * _Nullable, NSError * _Nullable))failure;
- (void)callFunctionWithFunctionName:(NSString * _Nonnull)functionName parameters:(NSDictionary * _Nonnull)parameters headers:(NSDictionary * _Nonnull)headers options:(NSDictionary * _Nonnull)options success:(void (^ _Nonnull)(id _Nullable))success failure:(void (^ _Nonnull)(NSString * _Nullable, NSString * _Nullable, NSError * _Nullable))failure;
- (NSString * _Nonnull)getOfflineStoreStatus SWIFT_WARN_UNUSED_RESULT;
- (id _Nullable)getOfflineParameterWithName:(NSString * _Nonnull)name error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (void)setOfflineParameterWithName:(NSString * _Nonnull)name value:(id _Nonnull)value;
- (NSString * _Nonnull)getPropertyTypeWithEntitySetName:(NSString * _Nonnull)entitySetName propertyName:(NSString * _Nonnull)propertyName SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)getVersion SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("ODataUpdater")
@interface ODataUpdater : BaseODataCruder
@end


SWIFT_CLASS_NAMED("ObjectCell")
@interface ObjectCellSwift : NSObject
/// Creates an Object Cell from SAP SDK SAPFiori
///
/// returns:
/// ObjectTableViewCell
+ (UITableViewCell * _Nonnull)create SWIFT_WARN_UNUSED_RESULT;
/// Populates an object cell with properties passed in params
/// \param params Dictionary containing keys as per metadata defintion
/// for ListObjectCell
/// (https://github.wdf.sap.corp/snowblind/metadata/blob/master/Definition%20Description/Pages/Controls/ListControl.md)
/// In addition, params also passes the cell to be updated in the “cell” key.
///
+ (void)populateWithParams:(NSDictionary * _Nonnull)params;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6SAPMDC23ObjectCollectionSection")
@interface ObjectCollectionSection : BaseSection
- (void)redrawWithData:(NSDictionary * _Nonnull)data;
- (void)updateRowWithIndex:(NSInteger)index data:(NSDictionary * _Nonnull)data;
@end


SWIFT_CLASS("_TtC6SAPMDC12ObjectHeader")
@interface ObjectHeader : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6SAPMDC19ObjectHeaderSection")
@interface ObjectHeaderSection : BaseSection
/// Sets new data in the FUIObjectHeader instance
/// <ul>
///   <li>
///     parameters:
///   </li>
///   <li>
///     data: The new header data to display
///   </li>
/// </ul>
- (void)redrawWithData:(NSDictionary * _Nonnull)data;
- (void)reloadDataWithItemCount:(NSInteger)itemCount;
- (void)reloadRowWithIndex:(NSInteger)index;
@end


SWIFT_CLASS("_TtC6SAPMDC18ObjectTableSection")
@interface ObjectTableSection : BaseTableSection
- (void)redrawWithData:(NSDictionary * _Nonnull)data;
- (void)updateRowWithIndex:(NSInteger)index data:(NSDictionary * _Nonnull)data;
- (void)setIndicatorStateWithParams:(NSDictionary * _Nonnull)params;
- (void)setSelectionModeWithParams:(NSDictionary * _Nonnull)params;
- (void)refreshIndicators;
@end

@class WelcomeScreenDelegate;

SWIFT_CLASS_NAMED("OnboardingController")
@interface OnboardingController : UINavigationController
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) OnboardingController * _Nonnull sharedInstance;)
+ (OnboardingController * _Nonnull)sharedInstance SWIFT_WARN_UNUSED_RESULT;
- (void)initialize:(NSDictionary * _Nonnull)params callback:(WelcomeScreenDelegate * _Nonnull)callback;
- (void)viewWillAppear:(BOOL)animated;
- (void)verifyPasscodeWithParams:(NSDictionary * _Nonnull)params resolve:(SnowblindPromiseResolveBlock _Nonnull)resolve reject:(SnowblindPromiseRejectBlock _Nonnull)reject;
- (void)unlockScreenWithResolve:(SnowblindPromiseResolveBlock _Nonnull)resolve reject:(SnowblindPromiseRejectBlock _Nonnull)reject;
- (void)restoreOnRelaunchWithParams:(NSDictionary * _Nonnull)params resolve:(SnowblindPromiseResolveBlock _Nonnull)resolve reject:(SnowblindPromiseRejectBlock _Nonnull)reject;
- (void)changeUserPasscodeWithResolve:(SnowblindPromiseResolveBlock _Nonnull)resolve reject:(SnowblindPromiseRejectBlock _Nonnull)reject;
- (void)reInitializePageWithParams:(NSDictionary * _Nonnull)params;
- (void)manageBlurScreenWithParams:(NSDictionary * _Nonnull)params;
- (nonnull instancetype)initWithNavigationBarClass:(Class _Nullable)navigationBarClass toolbarClass:(Class _Nullable)toolbarClass OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=5.0);
- (nonnull instancetype)initWithRootViewController:(UIViewController * _Nonnull)rootViewController OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("OnboardingCustomization")
@interface OnboardingCustomizationSwift : NSObject
+ (void)update:(NSDictionary * _Nonnull)params;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("OpenDocument")
@interface OpenDocumentSwift : NSObject
+ (void)openWithPath:(NSString * _Nonnull)path resolve:(SnowblindPromiseResolveBlock _Nonnull)resolve reject:(SnowblindPromiseRejectBlock _Nonnull)reject;
+ (void)clearCache;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@class UIPopoverPresentationController;

SWIFT_CLASS_NAMED("Popover")
@interface PopoverSwift : NSObject <UIPopoverPresentationControllerDelegate>
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) PopoverSwift * _Nonnull sharedInstance;)
+ (PopoverSwift * _Nonnull)sharedInstance SWIFT_WARN_UNUSED_RESULT;
- (void)showWithParams:(NSDictionary * _Nonnull)params resolve:(SnowblindPromiseResolveBlock _Nonnull)resolve reject:(SWIFT_NOESCAPE void (^ _Nonnull)(NSString * _Nullable, NSString * _Nullable, NSError * _Nullable))reject;
- (void)popoverPresentationControllerDidDismissPopover:(UIPopoverPresentationController * _Nonnull)popoverPresentationController;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class QLPreviewController;
@protocol QLPreviewItem;

SWIFT_CLASS("_TtC6SAPMDC17PreviewController")
@interface PreviewController : UIViewController <QLPreviewControllerDataSource, QLPreviewControllerDelegate>
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder SWIFT_UNAVAILABLE;
- (NSInteger)numberOfPreviewItemsInPreviewController:(QLPreviewController * _Nonnull)controller SWIFT_WARN_UNUSED_RESULT;
- (id <QLPreviewItem> _Nonnull)previewController:(QLPreviewController * _Nonnull)controller previewItemAtIndex:(NSInteger)index SWIFT_WARN_UNUSED_RESULT;
- (void)previewControllerDidDismiss:(QLPreviewController * _Nonnull)controller;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC6SAPMDC13ProfileHeader")
@interface ProfileHeader : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6SAPMDC20ProfileHeaderSection")
@interface ProfileHeaderSection : BaseSection
- (void)redrawWithData:(NSDictionary * _Nonnull)data;
- (void)reloadDataWithItemCount:(NSInteger)itemCount;
- (void)reloadRowWithIndex:(NSInteger)index;
@end

@class NSURL;

SWIFT_CLASS_NAMED("PushNotification")
@interface PushNotificationSwift : NSObject
- (nonnull instancetype)initWithApplicationId:(NSString * _Nonnull)applicationId baseUrl:(NSURL * _Nonnull)baseUrl deviceId:(NSString * _Nonnull)deviceId resolve:(SnowblindPromiseResolveBlock _Nonnull)resolve reject:(SnowblindPromiseRejectBlock _Nonnull)reject OBJC_DESIGNATED_INITIALIZER;
- (void)registerForPushNotification;
- (void)didFailToRegisterNotificationsWithError:(NSError * _Nonnull)error;
- (void)didRegisterForRemoteNotificationsWithDeviceToken:(NSData * _Nonnull)deviceToken;
- (void)unregisterForPushNotification;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("ReadParams")
@interface ReadParams : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("QueryOptionsReadParams")
@interface QueryOptionsReadParams : ReadParams
@end


SWIFT_CLASS_NAMED("ReadLinkReadParams")
@interface ReadLinkReadParams : ReadParams
@end


typedef SWIFT_ENUM(NSInteger, SBSecureStoreError, open) {
  SBSecureStoreErrorKeyNotFound = 0,
};
static NSString * _Nonnull const SBSecureStoreErrorDomain = @"SAPMDC.SBSecureStoreError";


SWIFT_CLASS("_TtC6SAPMDC6Search")
@interface Search : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class SectionDelegate;

SWIFT_CLASS("_TtC6SAPMDC14SectionFactory")
@interface SectionFactory : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) SectionFactory * _Nonnull sharedInstance;)
+ (SectionFactory * _Nonnull)sharedInstance SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (BaseSection * _Nullable)createSectionWithParams:(NSDictionary * _Nonnull)params callback:(SectionDelegate * _Nonnull)callback SWIFT_WARN_UNUSED_RESULT;
@end

@class UICollectionView;
@class UICollectionViewCell;
@class UIScrollView;
@class UISwipeActionsConfiguration;
@class UISearchController;
@class MFMessageComposeViewController;
@class MFMailComposeViewController;

SWIFT_RESILIENT_CLASS_NAMED("SectionedTableViewController")
@interface SectionedTableViewController : FUIFormTableViewController <MFMailComposeViewControllerDelegate, MFMessageComposeViewControllerDelegate, UICollectionViewDataSource, UICollectionViewDelegate, UIPopoverPresentationControllerDelegate, UISearchBarDelegate, UISearchResultsUpdating>
@property (nonatomic, strong) UITableView * _Nullable tableViewForExtension;
@property (nonatomic, strong) UITableViewCell * _Nullable tableViewCellForExtension;
@property (nonatomic) BOOL isInEmbeddedFrame;
- (void)initialize:(NSArray * _Nonnull)sections;
- (void)redraw:(NSArray * _Nonnull)sections;
- (void)viewWillAppear:(BOOL)animated;
- (void)collectionView:(UICollectionView * _Nonnull)collectionView willDisplayCell:(UICollectionViewCell * _Nonnull)cell forItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)viewDidAppear:(BOOL)animated;
- (void)viewDidLoad;
- (void)viewWillTransitionToSize:(CGSize)size withTransitionCoordinator:(id <UIViewControllerTransitionCoordinator> _Nonnull)coordinator;
- (void)viewDidLayoutSubviews;
- (NSInteger)numberOfSectionsInTableView:(UITableView * _Nonnull)tableView SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (void)scrollViewDidScroll:(UIScrollView * _Nonnull)scrollView;
- (void)tableView:(UITableView * _Nonnull)tableView willDisplayHeaderView:(UIView * _Nonnull)view forSection:(NSInteger)section;
- (void)tableView:(UITableView * _Nonnull)tableView willDisplayCell:(UITableViewCell * _Nonnull)cell forRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)tableView:(UITableView * _Nonnull)tableView didDeselectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)tableView:(UITableView * _Nonnull)tableView accessoryButtonTappedForRowWithIndexPath:(NSIndexPath * _Nonnull)indexPath;
+ (void)analyticViewTapWithSender:(AnalyticViewTapGestureRecogniser * _Nonnull)sender;
- (BOOL)tableView:(UITableView * _Nonnull)tableView canEditRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (UIView * _Nullable)tableView:(UITableView * _Nonnull)tableView viewForHeaderInSection:(NSInteger)sectionIndex SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForHeaderInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UIView * _Nullable)tableView:(UITableView * _Nonnull)tableView viewForFooterInSection:(NSInteger)sectionIndex SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForFooterInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UISwipeActionsConfiguration * _Nullable)tableView:(UITableView * _Nonnull)tableView leadingSwipeActionsConfigurationForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (UISwipeActionsConfiguration * _Nullable)tableView:(UITableView * _Nonnull)tableView trailingSwipeActionsConfigurationForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (UICollectionViewCell * _Nonnull)collectionView:(UICollectionView * _Nonnull)collectionView cellForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)collectionView:(UICollectionView * _Nonnull)collectionView numberOfItemsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (void)collectionView:(UICollectionView * _Nonnull)collectionView didSelectItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)updateSearchResultsForSearchController:(UISearchController * _Nonnull)searchController;
- (void)callSearchCallbackWithSender:(NSTimer * _Nonnull)sender;
- (void)searchBarSearchButtonClicked:(UISearchBar * _Nonnull)searchBar;
- (void)searchBarTextDidBeginEditing:(UISearchBar * _Nonnull)searchBar;
- (void)searchBarTextDidEndEditing:(UISearchBar * _Nonnull)searchBar;
- (BOOL)setSearchString:(NSString * _Nonnull)searchString SWIFT_WARN_UNUSED_RESULT;
- (void)scrollViewWillBeginDragging:(UIScrollView * _Nonnull)scrollView;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (void)viewWillDisappear:(BOOL)animated;
- (void)viewDidDisappear:(BOOL)animated;
- (void)messageComposeViewController:(MFMessageComposeViewController * _Nonnull)controller didFinishWithResult:(MessageComposeResult)result;
- (void)mailComposeController:(MFMailComposeViewController * _Nonnull)controller didFinishWithResult:(MFMailComposeResult)result error:(NSError * _Nullable)error;
- (void)popoverPresentationControllerDidDismissPopover:(UIPopoverPresentationController * _Nonnull)popoverPresentationController;
- (nonnull instancetype)initWithStyle:(UITableViewStyle)style OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6SAPMDC18SecureStoreManager")
@interface SecureStoreManager : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) SecureStoreManager * _Nonnull sharedInstance;)
+ (SecureStoreManager * _Nonnull)sharedInstance SWIFT_WARN_UNUSED_RESULT;
- (BOOL)putStringWithValue:(NSString * _Nonnull)value key:(NSString * _Nonnull)key error:(NSError * _Nullable * _Nullable)error;
- (NSString * _Nullable)getStringWithKey:(NSString * _Nonnull)key error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (BOOL)removeWithKey:(NSString * _Nonnull)key error:(NSError * _Nullable * _Nullable)error;
- (void)removeStore;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("SharedLoggerManager")
@interface SharedLoggerManagerSwift : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) SharedLoggerManagerSwift * _Nonnull sharedInstance;)
+ (SharedLoggerManagerSwift * _Nonnull)sharedInstance SWIFT_WARN_UNUSED_RESULT;
- (void)log:(NSString * _Nonnull)name withSeverity:(NSString * _Nullable)severity message:(NSString * _Nonnull)message;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6SAPMDC39SimplePropertyBarcodeScanViewController")
@interface SimplePropertyBarcodeScanViewController : UIViewController
/// :nodoc:
- (void)viewWillAppear:(BOOL)animated;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6SAPMDC31SimplePropertyCollectionSection")
@interface SimplePropertyCollectionSection : BaseSection
@end


SWIFT_CLASS("_TtC6SAPMDC13StylingHelper")
@interface StylingHelper : NSObject
+ (void)applySDKThemeWithFile:(NSString * _Nonnull)file;
+ (void)applySDKBrandingWithFile:(NSString * _Nonnull)file;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_PROTOCOL("_TtP6SAPMDC22SwiftExtensionDelegate_")
@protocol SwiftExtensionDelegate <NSObject>
- (void)setControlValueWithValue:(NSString * _Nonnull)value;
- (void)executeActionOrRuleWithDefinitionPath:(NSString * _Nonnull)definitionPath callback:(void (^ _Nonnull)(NSString * _Nonnull))callback;
- (void)resolveValueWithValue:(NSString * _Nonnull)value callback:(void (^ _Nonnull)(NSString * _Nonnull))callback;
@end


/// Passes typed calls to the NativeScript delegate
/// using performSelector. Handles callbacks as needed.
SWIFT_CLASS_NAMED("SwiftExtensionDelegateImpl")
@interface SwiftExtensionDelegateImpl : NSObject <SwiftExtensionDelegate>
@property (nonatomic, copy) void (^ _Nullable actionOrRuleCallback)(NSString * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable resolveValueCallback)(NSString * _Nonnull);
- (nonnull instancetype)initWith:(NSObject * _Nullable)nativeScriptDelegate OBJC_DESIGNATED_INITIALIZER;
- (void)setControlValueWithValue:(NSString * _Nonnull)value;
- (void)executeActionOrRuleWithDefinitionPath:(NSString * _Nonnull)definitionPath callback:(void (^ _Nonnull)(NSString * _Nonnull))callback;
- (void)resolveValueWithValue:(NSString * _Nonnull)value callback:(void (^ _Nonnull)(NSString * _Nonnull))callback;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("ToastMessageView")
@interface ToastMessageViewSwift : NSObject
/// Creates and displays a toast message from HCP SDK FioriUIKit
+ (void)displayToastMsgWithParams:(NSDictionary<NSString *, id> * _Nonnull)params;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end




@interface UINavigationController (SWIFT_EXTENSION(SAPMDC))
@property (nonatomic, readonly) UIStatusBarStyle preferredStatusBarStyle;
@end





SWIFT_CLASS_NAMED("VersionInfo")
@interface VersionInfoSwift : NSObject
+ (id _Nonnull)getVersionInfo SWIFT_WARN_UNUSED_RESULT;
+ (void)setVersionInfoWithVersion:(NSString * _Nonnull)version;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif
