module.exports = {
  src: [ 
    '../../../mdk-core/src/ClientEnums.ts',
    '../../../mdk-core/src/IView.ts',
    '../../../mdk-core/src/builders/odata/DataQueryBuilder.ts',
    '../../../mdk-core/src/context/ClientAPI.ts',
    '../../../mdk-core/src/context/IClientAPI.d.ts',
    '../../../mdk-core/src/context/Context.ts',
    '../../../mdk-core/src/context/IContext.ts',
    '../../../mdk-core/src/controls/BaseControl.ts',
    '../../../mdk-core/src/controls/IControl.ts',
    '../../../mdk-core/src/controls/IFilterable.ts',
    '../../../mdk-core/src/controls/PressedItem.ts',
    '../../../mdk-core/src/controls/SelectedItem.ts',
    '../../../mdk-core/src/data/ITargetSpecifier.d.ts',
    '../../../mdk-core/src/observables/IObservable.d.ts',
    '../../../mdk-core/src/utils/I18nHelper.ts',
    '../../../mdk-core/src/utils/ValueResolver.ts',
    '../../../mdk-core/src/utils/IAttachment.d.ts',
    '../../../src/SnowblindClientApplication/plugins/SAP/Foundation/Common/Logger/LoggerManager.ts',
    '../../../src/SnowblindClientApplication/sapmdc-declarations/extension-tableviewcell-handler/ios.d.ts'
  ],
  mode: 'file',
  includeDeclarations: true,
  tsconfig: '../../../src/SnowblindClientApplication/tsconfig.json',
  out: '../../../tmpapidocs/htmldoc',
  excludePrivate: true,
  excludeProtected: false,
  excludeExternals: true,
  name: 'Mobile Development Kit',
  readme: 'none',
  ignoreCompilerErrors: true,
  plugin: 'none',
  listInvalidSymbolLinks: true,
  hideGenerator: true
};